print("Hello,World Mashin Learning")
print("Error:")
print("---------------------------")
import numpy as np
a = np.matrix([[1,2],[3, 4]])
b = np.matrix([[1,2], [3,5]])
print("Array a:", a)
print("---------------------------")
print("Array b:", b)
print("---------------------------")
print("Multiply(a,b):")
c = np.multiply(a, b)
print(c)
print("---------------------------")
print("Np.dot(a,b):")
d = np.dot(a, b)
print(d)
print("---------------------------")
print("np.prod(a):")
e = np.prod(a)
print(e)
print("---------------------------")
print("Broadcasting:Source: a + 5")
f = a + 5 
print(f)
print("---------------------------")
print("Source: np.ones((3, 3))")
MyArray = np.ones((3, 3))
print(MyArray)
print("---------------------------")
print("Source: Broadcasting For np.ones([3, 3])")
MyBro = np.array([1, 2, 3])
MyBro1 = MyArray + MyBro
print(MyBro1)
print("---------------------------")
print("Source: Array(a)>>np.sum(a)")
Sum = np.sum(a)
print(Sum)
print("---------------------------")
print("Source: Array(a)>>np.cumsum(a, axis=0)")
cumsum = np.cumsum(a, axis=0)
print(cumsum)
print("---------------------------")
print("Source: np.math.sqrt(5)")
NpMath = np.math.sqrt(5)
print(NpMath)
print("---------------------------")